### ISSUE TITLE
New Req.

### ISSUE THREAD

**Issue by hazarbozkurt** [nikovega21/whatsapp-sticker-maker#1]
Thank you for this amazing project.
Can you add a sticker **store**?

Sorry for my bad English
Best regards..

**Comment by nikovega21** [comment]
Hi, thanks for the comment, I'll be working on it but give some time.

Regards

**Comment by hazarbozkurt** [comment]
Thank you very much for your reply.
Waiting Impatiently.
I don't doubt it's going to be enormous
